import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { parseCookies } from 'nookies'

export default function Home() {
  return (
    <>
      <Head>
        <title>Rifaz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favico.ico" />
      </Head>
      <main>
        <div>
          <Link href="login" >
            <button>
              login
            </button>
          </Link>

        </div>
      </main>
    </>
  )
}


export const getServerSideProps: GetServerSideProps = async (ctx) => {
  //const apiClient = GetApiClient(ctx);
  const { ['nextauth.token']: token } = parseCookies(ctx)

  if (!token) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      }
    }
  }

  return {
    redirect: {
      destination: '/home',
      permanent: false,
    }
  }
}